/*
 * Crypto-JS v2.4.0
 * http://code.google.com/p/crypto-js/
 * Copyright (c) 2011, Jeff Mott. All rights reserved.
 * http://code.google.com/p/crypto-js/wiki/License
 */
(function(h){function l(c,a){var b=c._blocksize*4;return b-a.length%b}var j=h.pad={},g=function(c){for(var a=c.pop(),b=1;b<a;b++)c.pop()};j.NoPadding={pad:function(){},unpad:function(){}};j.ZeroPadding={pad:function(c,a){var b=c._blocksize*4,d=a.length%b;if(d!=0)for(d=b-d;d>0;d--)a.push(0)},unpad:function(){}};j.iso7816={pad:function(c,a){var b=l(c,a);for(a.push(128);b>1;b--)a.push(0)},unpad:function(c){for(;c.pop()!=128;);}};j.ansix923={pad:function(c,a){for(var b=l(c,a),d=1;d<b;d++)a.push(0);a.push(b)},
unpad:g};j.iso10126={pad:function(c,a){for(var b=l(c,a),d=1;d<b;d++)a.push(Math.floor(Math.random()*256));a.push(b)},unpad:g};j.pkcs7={pad:function(c,a){for(var b=l(c,a),d=0;d<b;d++)a.push(b)},unpad:g};h=h.mode={};var i=h.Mode=function(c){if(c)this._padding=c};i.prototype={encrypt:function(c,a,b){this._padding.pad(c,a);this._doEncrypt(c,a,b)},decrypt:function(c,a,b){this._doDecrypt(c,a,b);this._padding.unpad(a)},_padding:j.iso7816};g=(h.ECB=function(){i.apply(this,arguments)}).prototype=new i;g._doEncrypt=
function(c,a){for(var b=c._blocksize*4,d=0;d<a.length;d+=b)c._encryptblock(a,d)};g._doDecrypt=function(c,a){for(var b=c._blocksize*4,d=0;d<a.length;d+=b)c._decryptblock(a,d)};g.fixOptions=function(c){c.iv=[]};g=(h.CBC=function(){i.apply(this,arguments)}).prototype=new i;g._doEncrypt=function(c,a,b){for(var d=c._blocksize*4,e=0;e<a.length;e+=d){if(e==0)for(var f=0;f<d;f++)a[f]^=b[f];else for(f=0;f<d;f++)a[e+f]^=a[e+f-d];c._encryptblock(a,e)}};g._doDecrypt=function(c,a,b){for(var d=c._blocksize*4,e=
0;e<a.length;e+=d){var f=a.slice(e,e+d);c._decryptblock(a,e);for(var k=0;k<d;k++)a[e+k]^=b[k];b=f}};g=(h.CFB=function(){i.apply(this,arguments)}).prototype=new i;g._padding=j.NoPadding;g._doEncrypt=function(c,a,b){var d=c._blocksize*4;b=b.slice(0);for(var e=0;e<a.length;e++){var f=e%d;f==0&&c._encryptblock(b,0);a[e]^=b[f];b[f]=a[e]}};g._doDecrypt=function(c,a,b){var d=c._blocksize*4;b=b.slice(0);for(var e=0;e<a.length;e++){var f=e%d;f==0&&c._encryptblock(b,0);var k=a[e];a[e]^=b[f];b[f]=k}};g=(h.OFB=
function(){i.apply(this,arguments)}).prototype=new i;g._padding=j.NoPadding;g._doEncrypt=function(c,a,b){var d=c._blocksize*4;b=b.slice(0);for(var e=0;e<a.length;e++){e%d==0&&c._encryptblock(b,0);a[e]^=b[e%d]}};g._doDecrypt=g._doEncrypt;h=(h.CTR=function(){i.apply(this,arguments)}).prototype=new i;h._padding=j.NoPadding;h._doEncrypt=function(c,a,b){for(var d=c._blocksize*4,e=0;e<a.length;){var f=b.slice(0);c._encryptblock(f,0);for(var k=0;e<a.length&&k<d;k++,e++)a[e]^=f[k];if(++b[d-1]==256){b[d-1]=
0;if(++b[d-2]==256){b[d-2]=0;if(++b[d-3]==256){b[d-3]=0;++b[d-4]}}}}};h._doDecrypt=h._doEncrypt})(Crypto);
